### ISSUE TITLE
Internal server error for test details

### ISSUE THREAD

**Issue by miminar** [openshift/test-infra#27]
When I access url https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16126/test_pull_request_origin_extended_image_registry/17/

I get Internal Server Error:

```
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~openshift-gce-devel/1.403799978271499909/view_base.py", line 89, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~openshift-gce-devel/1.403799978271499909/view_build.py", line 141, in get
    details = build_details(build_dir)
  File "/base/data/home/apps/s~openshift-gce-devel/1.403799978271499909/view_base.py", line 136, in wrapped
    data = func(*args)
  File "/base/data/home/apps/s~openshift-gce-devel/1.403799978271499909/view_build.py", line 119, in build_details
    failures.extend(parse_junit(junit, junit_futures[future]))
  File "/base/data/home/apps/s~openshift-gce-devel/1.403799978271499909/view_build.py", line 42, in parse_junit
    for result in yield_results(tree, "", filename):
  File "/base/data/home/apps/s~openshift-gce-devel/1.403799978271499909/view_build.py", line 54, in yield_results
    for result in yield_results(item, tree.attrib['name'], filename):
KeyError: 'name'
```
The url is contained in a [comment](https://github.com/openshift/origin/pull/16126#issuecomment-327746835) of openshift-ci-robot on openshift/origin#16126. Follows an original text of the comment:

----------

@miminar: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
ci/openshift-jenkins/extended_image_registry | 899b2fa8bb7f44ab13ec3c67cb51006965eb85e7 | [link](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16126/test_pull_request_origin_extended_image_registry/17/) | `/test extended_image_registry`

[Full PR test history](https://openshift-gce-devel.appspot.com/pr/16126). [Your PR dashboard](https://openshift-gce-devel.appspot.com/pr/miminar). Please help us cut down on flakes by [linking to](https://github.com/kubernetes/community/blob/master/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/openshift/origin/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://github.com/kubernetes/test-infra/blob/master/commands.md).
</details>

**Comment by kargakis** [comment]
@stevekuznetsov ptal

**Comment by stevekuznetsov** [comment]
This is in the jUnit parsing code ... some of your test suites or test cases don't have a name? ew.

**Comment by stevekuznetsov** [comment]
OK, fixed.
