### ISSUE TITLE
DownloadError: Unspecified error in fetching URL

### ISSUE THREAD

**Issue by kargakis** [openshift/test-infra#62]
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/apps/s~openshift-gce-devel/v20171107-5577434d.405360073934383629/view_base.py", line 56, in dispatch
    webapp2.RequestHandler.dispatch(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~openshift-gce-devel/v20171107-5577434d.405360073934383629/view_build.py", line 200, in get
    details = build_details(build_dir)
  File "/base/data/home/apps/s~openshift-gce-devel/v20171107-5577434d.405360073934383629/view_base.py", line 103, in wrapped
    data = func(*args)
  File "/base/data/home/apps/s~openshift-gce-devel/v20171107-5577434d.405360073934383629/view_build.py", line 149, in build_details
    parser.parse_xml(future.get_result(), path)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 383, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~openshift-gce-devel/v20171107-5577434d.405360073934383629/gcs_async.py", line 31, in get
    result = yield context.urlfetch(url, headers=headers)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 427, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 1291, in urlfetch
    result = yield rpc
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 513, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 453, in _get_fetch_result
    + url + error_detail)
DownloadError: Unspecified error in fetching URL: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/17115/test_pull_request_origin_integration/10607/artifacts/scripts/test-integration/artifacts/gotest_report_Sfr36.xml
```
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/17115/test_pull_request_origin_integration/10607/

@stevekuznetsov @mfojtik

**Comment by stevekuznetsov** [comment]
This could be a million things but often is a sizing issue... Gubernator can't handle logs of a certain size and our integration logs often are too large. Not sure we can do much about it except for showing the GCSWeb link when we fail... but in general Gubernator is very rough around the edges in these cases -- totally falls over without showing a nicer page if anything in `started.json` doesn't parse, for instance
